name: smarteval_flutter
description: SmartEval Flutter Application - AI-powered learning platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Navigation
  go_router: ^12.1.1
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  
  # Date & Time
  intl: ^0.18.1
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # File Picker
  file_picker: ^6.1.1
  
  # Image Picker
  image_picker: ^1.0.4
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Loading & Progress
  flutter_spinkit: ^5.2.0
  
  # Toast Messages
  fluttertoast: ^8.2.4
  
  # Charts
  fl_chart: ^0.65.0
  
  # Date Picker
  flutter_datetime_picker_plus: ^2.1.0
  
  # Markdown
  flutter_markdown: ^0.6.18
  
  # URL Launcher
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700